package com.cs407.memoMate

import android.os.Bundle
import android.view.*
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.fragment.app.Fragment
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.cs407.memoMate.Data.NoteDatabase
import com.cs407.memoMate.Data.Task
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class MainPageFragment : Fragment(), AddTaskMenu.TaskDialogListener {

    private lateinit var taskAdapter: TaskAdapter
    private val tasks = mutableListOf<Task>()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_main_page, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Initialize RecyclerView
        val recyclerView = view.findViewById<RecyclerView>(R.id.checklistRecyclerView)
        recyclerView.layoutManager = LinearLayoutManager(requireContext())
        taskAdapter = TaskAdapter(tasks)
        recyclerView.adapter = taskAdapter

        // Load tasks from database
        loadTasksFromDatabase()

        // Initialize Buttons
        val addButton = view.findViewById<Button>(R.id.addButton)
        val calendarButton = view.findViewById<Button>(R.id.calendarButton)
        val topButton = view.findViewById<Button>(R.id.topButton)
        val editButton = view.findViewById<Button>(R.id.editButton)

        addButton.setOnClickListener {
            val addTaskMenu = AddTaskMenu()
            addTaskMenu.setListener(this)
            addTaskMenu.show(parentFragmentManager, "AddTaskMenu")
        }

        editButton.setOnClickListener {
            showEditTaskDialog()
        }

        calendarButton.setOnClickListener {
            parentFragmentManager.beginTransaction()
                .replace(R.id.fragment_container, CalendarFragment())
                .addToBackStack(null)
                .commit()
        }

        topButton.setOnClickListener {
            parentFragmentManager.beginTransaction()
                .replace(R.id.fragment_container, UrgentImportantMatrixFragment())
                .addToBackStack(null)
                .commit()
        }

        val chatGPTButton = view.findViewById<Button>(R.id.chatgptButton)
        chatGPTButton.setOnClickListener {
            parentFragmentManager.beginTransaction()
                .replace(R.id.fragment_container, ChatGPTFragment())
                .addToBackStack(null)
                .commit()
        }
    }

    private fun loadTasksFromDatabase() {
        val db = NoteDatabase.getDatabase(requireContext())
        val taskDao = db.taskDao()

        lifecycleScope.launch(Dispatchers.IO) {
            val taskList = taskDao.getAllTasks()
            withContext(Dispatchers.Main) {
                tasks.clear()
                tasks.addAll(taskList)
                taskAdapter.notifyDataSetChanged()
            }
        }
    }

    private fun showEditTaskDialog() {
        val taskNames = tasks.map { it.noteTitle }.toTypedArray()
        val builder = AlertDialog.Builder(requireContext())
        builder.setTitle("Select Task to Edit")
            .setItems(taskNames) { _, which ->
                val selectedTask = tasks[which]
                val addTaskMenu = AddTaskMenu.newInstance(selectedTask)
                addTaskMenu.setListener(this)
                addTaskMenu.show(parentFragmentManager, "EditTaskMenu")
            }
        builder.show()
    }

    override fun onTaskAdded(
        name: String,
        ddl: String,
        isFinished: Boolean,
        note: String,
        importance: Int,
        task: Task?
    ) {
        val db = NoteDatabase.getDatabase(requireContext())
        val taskDao = db.taskDao()

        lifecycleScope.launch(Dispatchers.IO) {
            if (task == null) {
                // Adding a new task
                val newTask = Task(
                    noteId = 0, // Auto-generated by Room
                    significance = 0,
                    ddl = ddl,
                    finished = isFinished,
                    noteTitle = name,
                    noteAbstract = note,
                    importance = importance
                )

                // Prevent duplicate tasks with the same title and deadline
                val existingTasks = taskDao.getAllTasks()
                if (existingTasks.any { it.noteTitle == newTask.noteTitle && it.ddl == newTask.ddl }) {
                    withContext(Dispatchers.Main) {
                        Toast.makeText(requireContext(), "Task already exists.", Toast.LENGTH_SHORT).show()
                    }
                    return@launch
                }

                taskDao.insertTask(newTask)
            } else {
                // Editing an existing task
                val updatedTask = task.copy(
                    noteTitle = name,
                    ddl = ddl,
                    finished = isFinished,
                    noteAbstract = note,
                    importance = importance
                )
                taskDao.updateTask(updatedTask)
            }

            // Reload tasks to refresh UI
            loadTasksFromDatabase()
        }
    }
}
